#name: 01inputs
#on: workflow_dispatch
#
# inputs:
#    names:
#      description: Hello World
#      required: true
#
#    jobs:
#      print-name:
#      runs-on: ubuntu-latest
#
#      steps:
#        - name: Print the input name
#          run: echo  The name is ${{ inputs.names }}

name: 01inputs

on:
  workflow_dispatch:
    inputs:
      names:
        description: "Jagadeesh"
        required: true
        type: string

jobs:
  print-name:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name
        run: echo "The name is ${{ inputs.names }}"
          
