name: Hello World

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Print Date
        run: date

      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la
