name: Variables
on: workflow_dispatch

env:
  APP_NAME: roboshop
  APP_VERSION: 1.0

jobs:
  print-env:
    runs-on: ubuntu-latest

    steps:
      - name: step-1
        run: echo $APP_NAME
      - name: step2
        run: echo $APP_VERSION